esphome:
  name: housewatertank
  friendly_name: housewatertank
  on_boot:
    priority: -100
    then:
      - script.execute: take_quick_readings

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BVCrvwPOB+LRPeISWys6xbGYdSzlY5vVO8FTfdIApQ8="

ota:
- platform: esphome
  password: "b22c4a87fb42d70d859cf4eb946b81be"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.84
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  ap:
    ssid: "Sunnynet Fallback Hotspot"
    password: "E9V6weBr91DN"

captive_portal:

one_wire:
  - platform: gpio
    pin: GPIO4

globals:
  - id: warmup_done
    type: bool
    restore_value: no
    initial_value: "false"

script:
  - id: take_quick_readings
    mode: single
    then:
      - logger.log: "Starting sensor warm-up (20 quick readings)..."
      - lambda: |-
          id(warmup_done) = false;
      - repeat:
          count: 20
          then:
            - component.update: house_water_tank_distance
            - lambda: |-
                ESP_LOGI("warmup", "Reading: %.2f m", id(house_water_tank_distance).state);
            - delay: 2s
      - lambda: |-
          id(warmup_done) = true;
      - component.update: house_water_tank_distance
      - logger.log: "Warm-up complete. Starting regular reporting."

sensor:
  - platform: ultrasonic
    id: house_water_tank_distance
    name: "House Water Tank Distance"
    trigger_pin: GPIO14
    echo_pin: GPIO12
    update_interval: 60s
    timeout: 5m
    pulse_time: 10us
    accuracy_decimals: 2
    unit_of_measurement: "m"
    filters:
      - lambda: |-
          static float smoothed_distance = 0.0;
          float alpha = 0.2;
          smoothed_distance = (1 - alpha) * smoothed_distance + alpha * x;
          float max_height = 2.3;
          float sensor_min_distance = 0.0;
          float inverted_distance_val = max_height - (smoothed_distance - sensor_min_distance);
          return inverted_distance_val;
  #  internal: true  # hides during warm-up

  - platform: template
    name: "House Water Tank Percentage"
    unit_of_measurement: '%'
    accuracy_decimals: 0
    update_interval: 60s
    lambda: |-
      if (!id(warmup_done)) return NAN;
      float inverted = id(house_water_tank_distance).state;
      if (isnan(inverted)) return NAN;
      float percentage = (inverted * 100.0) / 2.3;
      return (int)round(max(0.0f, min(100.0f, percentage)));

  - platform: template
    name: "House Tank Volume"
    unit_of_measurement: "l"
    accuracy_decimals: 0
    update_interval: 60s
    lambda: |-
      if (!id(warmup_done)) return NAN;
      float h = id(house_water_tank_distance).state;
      if (isnan(h)) return NAN;
      float radius_cm = 250.0;
      float volume = 3.14159265359 * radius_cm * radius_cm * (h * 100.0) / 1000.0;
      return (int)round(max(0.0f, volume));

  - platform: dallas_temp
    name: "Tank Water Temperature"
    id: tank_water_temp
    update_interval: 60s
    unit_of_measurement: "°C"
    accuracy_decimals: 1
